# Generated by Django 5.1.1 on 2025-04-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sustainUbackend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="available_swipes",
            field=models.IntegerField(
                default=0, help_text="How many swipes this user has available right now"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(
                default=0, help_text="How many incentive points this user has right now"
            ),
        ),
    ]
